# vim: ft=dockerfile

# Not using python:3.7 here because team-gcc-arm-embedded/ppa does not support
# Ubuntu Cosmic or Debian Stretch, and Alpine, bizarrely, does not seem to
# package GCC cross compilers
FROM python:3.7-alpine

RUN apk update && apk add alpine-sdk curl wget ssh rsync git git-lfs
RUN pip install pipenv
