import unittest

from kmk.keys import KC
from kmk.modules.capsword import CapsWord
from kmk.modules.layers import Layers
from kmk.modules.modtap import ModTap
from kmk.modules.tapdance import TapDance
from tests.keyboard_test import KeyboardTest


class TestCapsWord(unittest.TestCase):
    def test_basic_kmk_keyboard(self):
        keyboard = KeyboardTest(
            [CapsWord(False), Layers(), ModTap(), TapDance()],
            [
                [
                    KC.CW,
                    KC.B,
                    KC.C,
                    KC.COMMA,
                    KC.UNDS,
                    KC.MO(1),
                    KC.MT(KC.COMMA, KC.LCTRL),
                    KC.LT(1, KC.D),
                    KC.TD(KC.A, KC.COMMA),
                ],
                [KC.A, KC.B, KC.D, KC.N4, KC.N5, KC.A, KC.B],
                [KC.N1, KC.N2, KC.N3, KC.N4, KC.N5, KC.A, KC.B],
            ],
            debug_enabled=False,
        )

        keyboard.test(
            'basic capsword behaviour',
            [
                (0, True),
                (0, False),
                (1, True),
                (1, False),
                (0, True),
                (0, False),
                (1, True),
                (1, False),
            ],
            [
                {KC.LSFT, KC.B},
                {},
                {KC.B},
                {},
            ],
        )

        keyboard.test(
            'capsword with ignore keys',
            [
                (0, True),
                (0, False),
                50,
                (4, True),
                (4, False),
                50,
                (1, True),
                (1, False),
                50,
                (3, True),
                (3, False),
                50,
                (2, True),
                (2, False),
                50,
                (0, True),
                (0, False),
                50,
                (2, True),
                (2, False),
                50,
                (0, True),
                (0, False),
                50,
            ],
            [
                {KC.LSFT, KC.MINS},
                {},
                {KC.LSFT, KC.B},
                {},
                {KC.COMMA},
                {},
                {KC.C},
                {},
                {KC.LSFT, KC.C},
                {},
            ],
        )

        keyboard.test(
            'capsword with rollover keys',
            [
                (0, True),
                (0, False),
                (4, True),
                (1, True),
                (4, False),
                (1, False),
                (3, True),
                (3, False),
                (2, True),
                (2, False),
                (0, True),
                (0, False),
                (2, True),
                (2, False),
                (0, True),
                (0, False),
            ],
            [
                {KC.LSFT, KC.UNDS},
                {KC.LSFT, KC.B, KC.UNDS},
                {KC.LSFT, KC.B},
                {},
                {KC.COMMA},
                {},
                {KC.C},
                {},
                {KC.LSFT, KC.C},
                {},
            ],
        )

        keyboard.test(
            'capsword with mod tap ',
            [
                (0, True),
                (0, False),
                50,
                (6, True),
                350,
                (6, False),
                (2, True),
                (2, False),
                50,
                (6, True),
                100,
                (6, False),
                50,
                (2, True),
                (2, False),
                50,
            ],
            [
                {KC.LCTL},
                {},
                {KC.LSFT, KC.C},
                {},
                {KC.COMMA},
                {},
                {KC.C},
                {},
            ],
        )

        keyboard.test(
            'capsword with mod tap and layer',
            [
                (0, True),
                (0, False),
                50,
                (2, True),
                (2, False),
                50,
                (6, True),
                350,
                (6, False),
                (2, True),
                (2, False),
                50,
                (6, True),
                150,
                (6, False),
                (2, True),
                (2, False),
                50,
                (0, True),
                (0, False),
                50,
                (5, True),
                250,
                (2, True),
                (2, False),
                50,
                (5, False),
                50,
                (0, True),
                (0, False),
            ],
            [
                {KC.LSFT, KC.C},
                {},
                {KC.LCTL},
                {},
                {KC.LSFT, KC.C},
                {},
                {KC.COMMA},
                {},
                {KC.C},
                {},
                {KC.D, KC.LSFT},
                {},
            ],
        )

        keyboard.test(
            'capsword with layer',
            [
                (0, True),
                (0, False),
                (5, True),
                250,
                (2, True),
                (2, False),
                (5, False),
                (2, True),
                (2, False),
                (0, True),
                (0, False),
                (2, True),
                (2, False),
            ],
            [
                {KC.LSFT, KC.D},
                {},
                {KC.LSFT, KC.C},
                {},
                {KC.C},
                {},
            ],
        )

        keyboard.test(
            'capsword with mod tap and layer 2',
            [
                (0, True),
                (0, False),
                (6, True),
                100,
                (6, False),
                (0, True),
                (0, False),
                (7, True),
                300,
                (2, True),
                (2, False),
                (7, False),
                100,
                (7, True),
                (7, False),
                (2, True),
                (2, False),
                (0, True),
                (0, False),
                (2, True),
                (2, False),
            ],
            [
                {KC.COMMA},
                {},
                {KC.LSFT, KC.D},
                {},
                {KC.LSFT, KC.D},
                {},
                {KC.LSFT, KC.C},
                {},
                {KC.C},
                {},
            ],
        )

        keyboard.test(
            'capsword tap dance behaviour',
            [
                (0, True),
                (0, False),
                (8, True),
                (8, False),
                310,
                (8, True),
                (8, False),
                150,
                (8, True),
                (8, False),
                200,
                (2, True),
                (2, False),
                (0, True),
                (0, False),
                (2, True),
                (2, False),
                (0, True),
                (0, False),
            ],
            [
                {KC.A, KC.LSFT},
                {},
                {KC.COMMA},
                {},
                {KC.C},
                {},
                {KC.C, KC.LSFT},
                {},
            ],
        )


if __name__ == '__main__':
    unittest.main()
