"""
This type stub file was generated by pyright.
"""

import _bleio
from ..characteristics import Characteristic, ComplexCharacteristic

"""

This module provides the top level Service definition.

"""
__version__ = ...
__repo__ = ...
class Service:
    """Top level Service class that handles the hard work of binding to a local or remote service.

    Providers of a local service should instantiate their Service with service=None, the default.
    The local Service's characteristics will be lazily made available to clients as they are used
    locally. In other words, a characteristic won't be available to remote clients until it has
    been read or written locally.

    To use a remote Service, get the item with the key of the Service type on the
    `BLEConnection`. For example, ``connection[UartService]`` will return the UartService
    instance for the connection's peer.
    """
    def __init__(self, *, service=..., secondary=..., **initial_values) -> None:
        ...
    
    @property
    def remote(self): # -> bool:
        """True if the service is provided by a peer and accessed remotely."""
        ...
    


