"""
This type stub file was generated by pyright.
"""

from . import ComplexCharacteristic

"""
`stream`
====================================================

This module provides stream characteristics that bind readable or writable objects to the Service
object they are on.

"""
__version__ = ...
__repo__ = ...
class BoundWriteStream:
    """Writes data out to the peer."""
    def __init__(self, bound_characteristic) -> None:
        ...
    
    def write(self, buf): # -> None:
        """Write data from buf out to the peer."""
        ...
    


class StreamOut(ComplexCharacteristic):
    """Output stream from the Service server."""
    def __init__(self, *, uuid=..., timeout=..., buffer_size=..., properties=..., read_perm=..., write_perm=...) -> None:
        ...
    
    def bind(self, service): # -> CharacteristicBuffer | BoundWriteStream:
        """Binds the characteristic to the given Service."""
        ...
    


class StreamIn(ComplexCharacteristic):
    """Input stream into the Service server."""
    def __init__(self, *, uuid=..., timeout=..., buffer_size=..., properties=..., write_perm=...) -> None:
        ...
    
    def bind(self, service): # -> BoundWriteStream | CharacteristicBuffer:
        """Binds the characteristic to the given Service."""
        ...
    


