name: Build
on:
  push:
    branches: ['main', 'stage-workflows']
    paths:
      - 'kmk/**'
      - '.github/workflows/compile.yml'
env:
  mpy-cross-path: "https://adafruit-circuit-python.s3.amazonaws.com/bin/mpy-cross/linux-amd64/mpy-cross-linux-amd64-"
jobs:
  Compile:
    strategy:
      matrix:
        # Check https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/mpy-cross/linux-amd64/ to get the latest version
        mpy-cross-release: ["8.2.10", "9.0.5", "9.2.1"]
    runs-on: ubuntu-24.04
    steps:
      - run: echo "A ${{ github.event_name }} event trigged build of branch ${{ github.ref }}, repository ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Cache mpy-cross
        id: cache-mpy-cross
        uses: actions/cache@v4
        env:
          cache-name: cache-mpy-cross
        with:
          path: ${{ github.workspace }}/mpy-cross
          key: ${{ matrix.mpy-cross-release }}
      - if: ${{ steps.cache-mpy-cross.outputs.cache-hit != 'true' }}
        name: install mpy-cross
        run: |
          wget --no-verbose "${{ env.mpy-cross-path }}${{ matrix.mpy-cross-release }}.static" -O ${{ github.workspace }}/mpy-cross; \
          chmod +x ${{ github.workspace }}/mpy-cross

      - name: get short git sha
        id: sha
        run: echo "SHA=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT

      - name: compile
        run: PATH=.:$PATH make compile
      - name: List build dir
        run: |
          ls -la .compiled/kmk/
      - name: upload zip
        uses: actions/upload-artifact@v4
        with:
          name: kmk-${{ steps.sha.outputs.SHA }}+mpy-cross-${{ matrix.mpy-cross-release }}
          path: .compiled/kmk/
