name: Spellcheck
on:
  push:
    paths:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install aspell
      - run: make spellcheck
